// types/Athlete.ts

export interface Athlete {
  athleteId?: number; //autogenerated by database
  athleteFirstName: string;
  athleteLastName: string;
  birthday: string;
  gender: string; //can this be set to options?
  team: string;
	ageGroup: string;
}