// types/Athlete.ts
import type { TeamMembership } from "./TeamMembership";

export interface Athlete {
  athleteId?: number; // autogenerated by database

  athleteFirstName: string;
  athleteLastName: string;
  birthday: string;
  gender: string;

  acaId?: number | null;
  fisId?: number | null;
  ageGroup?: string | null;
  
  teamMemberships?: TeamMembership[];

}