// types/Session.ts

export interface Session {
  id?: number; //autogenerated by database
  sessionDay: string;
  location: string;
  discipline?: string;
  snowConditions?: string;
  visConditions?: string;
  terrainType?: string;
  numFreeskiRuns?: number;
  numDrillRuns?: number;
  numCourseRuns?: number;
  generalComments?: string;
}
