// types/Session.ts

import type { Attendance } from "./Attendance";
import type { Team } from "./Team";

export interface Session {
  sessionId?: number; //autogenerated by database
  sessionDay: string;
  startTime: string;
  endTime: string;
  location: string;
  discipline?: string;
  snowConditions?: string;
  visConditions?: string;
  terrainType?: string;
  numFreeskiRuns?: number;
  numDrillRuns?: number;
  numEducationalCourseRuns?: number; 
  numGatesEducationalCourse?: number; 
  numRaceTrainingCourseRuns?: number;
  numGatesRaceTrainingCourse?: number;
  numRaceRuns?: number;
  numGatesRace?: number;
  generalComments?: string;
  attendance?: number[];
  receivedAttendance?: Attendance[];
  createdBy?: number;
  teams?: Team[];
  teamIds?: number[];
}
