// types/User.ts

export interface User {
  userId?: number; //autogenerated by database
  userFirstName: string;
  userLastName: string;
  email: string;
  password?: string;
  password2?: string;
  status: string;
}



